# Generated by Django 4.1.6 on 2023-02-10 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datastore',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='datastore',
            name='item_price',
        ),
        migrations.AddField(
            model_name='datastore',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2023, 2, 10, 6, 49, 23, 337816)),
        ),
        migrations.AddField(
            model_name='datastore',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2023, 2, 10, 6, 49, 23, 337825)),
        ),
        migrations.AddField(
            model_name='datastore',
            name='raw_data',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='datastore',
            name='search_query',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
