# Generated by Django 4.1.6 on 2023-02-10 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_store', '0002_remove_datastore_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastore',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2023, 2, 10, 13, 39, 55, 198350)),
        ),
        migrations.AlterField(
            model_name='datastore',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2023, 2, 10, 13, 39, 55, 198358)),
        ),
        migrations.AlterField(
            model_name='datastore',
            name='raw_data',
            field=models.JSONField(default=[], null=True),
        ),
    ]
