# Generated by Django 4.1.6 on 2023-02-13 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_store', '0005_datastore_status_alter_datastore_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastore',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2023, 2, 13, 7, 17, 56, 22926)),
        ),
        migrations.AlterField(
            model_name='datastore',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2023, 2, 13, 7, 17, 56, 22935)),
        ),
        migrations.AlterField(
            model_name='datastore',
            name='status',
            field=models.CharField(default='fetching', max_length=10, null=True),
        ),
    ]
