# Generated by Django 4.1.6 on 2023-02-13 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_store', '0006_alter_datastore_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastore',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2023, 2, 13, 7, 18, 40, 132307)),
        ),
        migrations.AlterField(
            model_name='datastore',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2023, 2, 13, 7, 18, 40, 132316)),
        ),
        migrations.AlterField(
            model_name='datastore',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
